[package]
name = "filite"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
cfg-if = "0.1.10"
chrono = "0.4.9"
dirs = "2.0.2"
num_cpus = "1.10.1"
toml = "0.5.3"
[dependencies.diesel]
version = "1.4.2"
features = ["r2d2", "sqlite"]
[dependencies.libsqlite3-sys]
version = "0.12.0"
features = ["bundled"]
[dependencies.serde]
version = "1.0.101"
features = ["derive"]

[target.'cfg(debug_assertions)'.dependencies]
dotenv = "0.14.1"
