[package]
name = "filite"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
description = "A simple, light and standalone pastebin, URL shortener and file-sharing service"

[dependencies]
actix-files = "0.1.6"
actix-identity = "0.1.0"
actix-web = "1.0.8"
base64 = "0.10.1"
blake2 = "0.8.1"
chrono = "0.4.9"
diesel_migrations = "1.4.0"
dirs = "2.0.2"
dotenv = { version = "0.14.1", optional = true }
env_logger = "0.7.1"
futures = "0.1.29"
num_cpus = "1.10.1"
toml = "0.5.3"
[dependencies.diesel]
version = "1.4.3"
features = ["r2d2", "sqlite"]
[dependencies.libsqlite3-sys]
version = "0.16.0"
features = ["bundled"]
[dependencies.serde]
version = "1.0.101"
features = ["derive"]

[features]
default = []
dev = ["dotenv"]
