[package]
name = "filite"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"

[dependencies]
actix-files = "0.1.5"
actix-web = "1.0.8"
base64 = "0.10.1"
chrono = "0.4.9"
dirs = "2.0.2"
env_logger = "0.7.0"
futures = "0.1.29"
num_cpus = "1.10.1"
[dependencies.diesel]
version = "1.4.2"
features = ["r2d2", "sqlite"]
[dependencies.libsqlite3-sys]
version = "0.12.0"
features = ["bundled"]
[dependencies.serde]
version = "1.0.101"
features = ["derive"]

[target.'cfg(debug_assertions)'.dependencies]
dotenv = "0.14.1"

[target.'cfg(not(debug_assertions))'.dependencies]
toml = "0.5.3"
