[package]
name = "filite"
version = "0.3.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
description = "A simple, light and standalone pastebin, URL shortener and file-sharing service"
homepage = "https://github.com/raftario/filite"
repository = "https://github.com/raftario/filite"
readme = "README.md"
keywords = [
    "file-sharing",
    "url-shortener",
    "pastebin"
]
license = "MIT"

[dependencies]
dotenv = { version = "0.15.0", optional = true }
chrono = "0.4.11"
env_logger = "0.7.1"
envy = "0.4.1"
log = "0.4.8"
rusqlite = { version = "0.23.1", features = ["bundled", "chrono"] }
rust-argon2 = "0.8.2"
serde = { version = "1.0.112", features = ["derive"] }
tokio = { version = "0.2.21", features = ["blocking", "fs", "macros"] }
toml = "0.5.6"
warp = { version = "0.2.3", features = ["multipart", "tls"], default-features = false }

[features]
default = []
dev = ["dotenv"]
