name: Checks
on: [pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - run: rustup component add rustfmt
    - run: rustup component add clippy
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Check for clippy warnings
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
